package testPackage;

import static org.junit.Assert.*;
import sourcePackage.*;

import org.junit.Test;
import org.junit.Before;
import java.util.List;

import sourcePackage.Game;
import sourcePackage.Player;
import sourcePackage.Position;
import static org.hamcrest.CoreMatchers.*;


public class PlayerTest{


	@Before
	public void Before() {
		Game.game.setNumPlayers(4);
		Game.game.players[0]=new Player();
		Game.game.players[1]=new Player();
		Game.game.players[2]=new Player();
		Game.game.players[3]=new Player();

		Map map = SafeMap.getInstance(5,5);
		Game.game.mapSize=5;
		map.setSize(5,5);
		map.generate();
		
	
		
	}
	
	@Test
	public void setStartPositionTest(){
		Position p1 = Game.game.players[0].setStartPosition();
		Position p2 = Game.game.players[1].setStartPosition();
		
		//p1!=p2
		assertNotEquals(p1,p2);
		
		//variable startPosition for each player is storing the actual start position generated by method
		assertEquals(Game.game.players[0].startPosition, p1);
		assertEquals(Game.game.players[1].startPosition, p2);

		//checking that each start position generated is a green tile
		assertEquals('a', Map.map.getTileType((Game.game.players[0].startPosition.x),(Game.game.players[0].startPosition.y)));
		assertEquals('a', Map.map.getTileType((Game.game.players[1].startPosition.x),(Game.game.players[1].startPosition.y)));
		
	}
	
	@Test
	public void setPositionTest(){
		Game.game.players[0].position.x=0;
		Game.game.players[0].position.y=0;
		Game.game.players[1].position.x=2;
		Game.game.players[1].position.y=3;
		
		Position p0 = new Position();
		p0.x=-1;
		p0.y=-1;
		
		Position p1 = new Position();
		p1.x=4;
		p1.y=3;
		
		Position p01 = new Position();
		p01.x=0;
		p01.y=1;
		
		Position p11 = new Position();
		p11.x=2;
		p11.y=4;
		
		Position p12 = new Position();
		p12.x=0;
		p12.y=5;
		
		//out of bounds position 
		assertEquals(false, Game.game.players[0].setPosition(p0));		
		assertEquals(false, Game.game.players[1].setPosition(p12));

		//set position to a tile where 2 or more moves are needed
		assertEquals(false, Game.game.players[0].setPosition(p1));
		assertEquals(false, Game.game.players[1].setPosition(p12));

		
		//good positions
		assertEquals(true, Game.game.players[0].setPosition(p01));
		assertEquals(true, Game.game.players[1].setPosition(p11));
		
		
	}
	
	@Test
	public void MoveTest(){
		Game.game.players[0].position.x=4;
		Game.game.players[0].position.y=0;
		Game.game.players[1].position.x=4;
		Game.game.players[1].position.y=4;
		Game.game.players[2].position.x=0;
		Game.game.players[2].position.y=0;
		Game.game.players[3].position.x=0;
		Game.game.players[3].position.y=4;


		//Up
		assertEquals(true, Game.game.players[0].move('U'));
		//Down
		assertEquals(true, Game.game.players[0].move('D'));
		//Left
		assertEquals(true,Game.game.players[0].move('L') );


		//Left
		assertEquals(true, Game.game.players[1].move('L'));
		//Right
		assertEquals(true, Game.game.players[1].move('R'));
		//down
		assertEquals(true, Game.game.players[1].move('D'));

		//Up
		assertEquals(true, Game.game.players[2].move('U'));
//Right
		assertEquals(true, Game.game.players[3].move('R'));

		//Wrong input
		assertEquals(false, Game.game.players[1].move('B'));
		

	}
	
	
	@Test
	public void updateTest(){
		Position p = new Position();
		Position p1 = new Position();
		p.x = 0;
		p.y = 2;
		p1.x = 1;
		p1.y = 2;
		Game.game.players[0].visitedPositions.add(p);
		
		//test to check that the required array is being returned by the getUpdateMethod
		List<Position> testPositions = Game.game.players[0].getUpdate();
		assertEquals(Game.game.players[0].visitedPositions, testPositions);
		
		//adding a new position to the visited positions array of player 0
		Game.game.players[0].visitedPositions.add(p1);
		//test positions is updated to reflect the new addition to the array
		testPositions = Game.game.players[0].visitedPositions;
		Game.game.players[0].setUpdate(Game.game.players[0].visitedPositions);
		
		//checking that the visitedPositions array is updated after this change
		Game.game.players[0].update();
		assertEquals(Game.game.players[0].visitedPositions, testPositions);
		
	}
	
}
